# Generated by Django 4.2.16 on 2024-11-26 01:54

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=255, unique=True, verbose_name='Username')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('first_name', models.CharField(max_length=255, verbose_name='First name')),
                ('last_name', models.CharField(max_length=255, verbose_name='Last name')),
                ('balance', models.DecimalField(decimal_places=2, default=50, max_digits=18, verbose_name='Balance')),
                ('verification_code', models.CharField(blank=True, default=core.models.User.create_verification_code, max_length=6, verbose_name='Verification code')),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name='Registration date')),
                ('is_active', models.BooleanField(default=False, verbose_name='User is active')),
                ('is_staff', models.BooleanField(default=False, verbose_name='User is staff')),
                ('balance_replenishment_notification', models.BooleanField(default=True, verbose_name='Balance replenishment notification')),
                ('purchase_notification', models.BooleanField(default=True, verbose_name='Purchase notification')),
                ('filled_cart_notification', models.BooleanField(default=True, verbose_name='Filled cart notification')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(blank=True, verbose_name='Email host')),
                ('port', models.CharField(blank=True, verbose_name='Email port')),
                ('login', models.EmailField(blank=True, max_length=254, verbose_name='Email login')),
                ('password', models.CharField(blank=True, verbose_name='Email Password')),
                ('use_tls', models.BooleanField(default=False, verbose_name='Use TLS')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LoginSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_simultaneous_logins', models.PositiveIntegerField(default=5, help_text='The maximum number of devices a user can be logged in simultaneously.', verbose_name='Maximum Simultaneous Logins')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('name', models.TextField(verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='SessionWithUser',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='session key')),
                ('session_data', models.TextField(verbose_name='session data')),
                ('expire_date', models.DateTimeField(db_index=True, verbose_name='expire date')),
                ('user_id', models.IntegerField(db_index=True, null=True)),
                ('date_created', models.DateTimeField(null=True)),
            ],
            options={
                'verbose_name': 'session',
                'verbose_name_plural': 'sessions',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SVGLifetimeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lifetime', models.PositiveIntegerField(default=120, help_text='The time in minutes during which the svg image will be available after conversion.', verbose_name='SVG Lifetime')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='WishlistImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
